// Enable POSIX.1-2008 API functions (e.g. clock_gettime) when compiling with
// strict -std=c99
#define _POSIX_C_SOURCE 200809L

#if defined(__EMSCRIPTEN__)
#define SOKOL_GLES3
#elif defined(_WIN32)
#define SOKOL_D3D11
#elif defined(__APPLE__)
#define SOKOL_METAL
#elif defined(__linux__)
#define SOKOL_GLCORE
#endif

#define SOKOL_IMPL
#include "sokol_app.h"
#include "sokol_gfx.h"
#include "sokol_glue.h"
#include "sokol_log.h"

// include generated shaders file
#include "shaders/triangle.glsl.h"

// Include Nuklear UI single-header library
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_IMPLEMENTATION
#include "nuklear.h"

#define SOKOL_NUKLEAR_IMPL
#include "util/sokol_nuklear.h"

typedef struct {
  float position[3];
  float color[4];
} vertex_t;

static struct {
  sg_pipeline pip;
  sg_bindings bind;
  sg_pass_action pass_action;
  float bg_color[3];
} state;

static void init(void) {
  sg_setup(&(sg_desc){
      .environment = sglue_environment(),
      .logger.func = slog_func,
  });

  snk_setup(&(snk_desc_t){
      .dpi_scale = sapp_dpi_scale(),
      .logger.func = slog_func,
      .enable_set_mouse_cursor = true,
  });

  state.bg_color[0] = 0.1f;
  state.bg_color[1] = 0.1f;
  state.bg_color[2] = 0.12f;

  // 3 vertices forming a triangle with RGB colors
  vertex_t vertices[] = {
      // position           // color (r, g, b, a)
      {{0.0f, 0.5f, 0.5f}, {1.0f, 0.0f, 0.0f, 1.0f}},  // Top (Red)
      {{0.5f, -0.5f, 0.5f}, {0.0f, 1.0f, 0.0f, 1.0f}}, // Bottom Right (Green)
      {{-0.5f, -0.5f, 0.5f}, {0.0f, 0.0f, 1.0f, 1.0f}} // Bottom Left (Blue)
  };

  // Create vertex buffer
  state.bind.vertex_buffers[0] = sg_make_buffer(&(sg_buffer_desc){
      .data = SG_RANGE(vertices), .label = "triangle-vertices"});

  // Create shader using the descriptor auto-generated by sokol-shdc
  sg_shader shd = sg_make_shader(triangle_shader_desc(sg_query_backend()));

  // Create pipeline object
  state.pip = sg_make_pipeline(&(sg_pipeline_desc){
      .shader = shd,
      .layout =
          {.attrs =
               {[ATTR_triangle_position] = {.format = SG_VERTEXFORMAT_FLOAT3},
                [ATTR_triangle_color] = {.format = SG_VERTEXFORMAT_FLOAT4}}},
      .label = "triangle-pipeline"});

  // Pass action setup
  state.pass_action =
      (sg_pass_action){.colors[0] = {.load_action = SG_LOADACTION_CLEAR,
                                     .clear_value = {
                                         state.bg_color[0],
                                         state.bg_color[1],
                                         state.bg_color[2],
                                         1.0f,
                                     }}};
}

static void frame(void) {
  // Build Nuklear UI
  struct nk_context *ctx = snk_new_frame();

  nk_style_hide_cursor(ctx);

  if (nk_begin(ctx, "Sample UI Control", nk_rect(20, 20, 260, 240),
               NK_WINDOW_BORDER | NK_WINDOW_MOVABLE | NK_WINDOW_SCALABLE |
                   NK_WINDOW_MINIMIZABLE | NK_WINDOW_TITLE)) {
    nk_layout_row_dynamic(ctx, 25, 1);
    nk_label(ctx, "Background Clear Color:", NK_TEXT_LEFT);

    nk_layout_row_dynamic(ctx, 25, 1);
    nk_property_float(ctx, "Red:", 0.0f, &state.bg_color[0], 1.0f, 0.01f,
                      0.005f);
    nk_property_float(ctx, "Green:", 0.0f, &state.bg_color[1], 1.0f, 0.01f,
                      0.005f);
    nk_property_float(ctx, "Blue:", 0.0f, &state.bg_color[2], 1.0f, 0.01f,
                      0.005f);

    nk_layout_row_dynamic(ctx, 30, 1);
    if (nk_button_label(ctx, "Reset Background")) {
      state.bg_color[0] = 0.1f;
      state.bg_color[1] = 0.1f;
      state.bg_color[2] = 0.12f;
    }
  }
  nk_end(ctx);

  // Update clear color
  state.pass_action.colors[0].clear_value.r = state.bg_color[0];
  state.pass_action.colors[0].clear_value.g = state.bg_color[1];
  state.pass_action.colors[0].clear_value.b = state.bg_color[2];

  // Begin render pass
  sg_begin_pass(
      &(sg_pass){.action = state.pass_action, .swapchain = sglue_swapchain()});

  // Draw triangle
  sg_apply_pipeline(state.pip);
  sg_apply_bindings(&state.bind);
  sg_draw(0, 3, 1);

  // Draw Nuklear UI on top
  snk_render(sapp_width(), sapp_height());

  sg_end_pass();
  sg_commit();
}

static void event(const sapp_event *ev) { snk_handle_event(ev); }

static void cleanup(void) {
  snk_shutdown();
  sg_shutdown();
}

sapp_desc sokol_main(int argc, char *argv[]) {
  (void)argc;
  (void)argv;
  return (sapp_desc){
      .init_cb = init,
      .frame_cb = frame,
      .event_cb = event,
      .cleanup_cb = cleanup,
      .width = 800,
      .height = 600,
      .high_dpi = true,
      .window_title = "Sokol Triangle + Nuklear Starter",
      .icon.sokol_default = true,
      .logger.func = slog_func,
  };
}
